### ISSUE TITLE
Multiline output in //CALL

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#10]
codecheck-bj-4-loop-107 cannot work. Each output is more than one line. Remedy: If output contains newlines, print as

actual
\n
expected
\n
status

What if it has multiple newlines? Use one more than the longest newline???

**Comment by cayhorstmann** [comment]
https://codecheck.io/files/wiley/codecheck-bj-4-loop-107

**Comment by agill18** [comment]
I will take up this issue.
