### ISSUE TITLE
Show student URL in edit screen

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#17]
Right now, when one views a https://codecheck.io/private/problem/id/KEY, one must click on Submit Changes to get the student URL. That's not so nice if one reviews an existing problem since one may well be nervous about changing it. Make it so that the student URL is displayed.

**Comment by AlexanderChang140** [comment]
I'm working on this.

**Comment by cayhorstmann** [comment]
#52
