### ISSUE TITLE
For development, store assignments in file system

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#23]
It is a hassle that an AWS DynamoDB is required for local development. We want to imitate what is done for S3. When there is no AWS account, data should be stored locally. The root directory is specified by the config key `com.horstmann.codecheck.db`. It has subdirectories for each DynamoDB table: `Assignments`, `LTICredentials`, and so on. Use subdirectories for the partition key and, when present, the sort key.

**Comment by odiaz95012** [comment]
@thinh241819 and I are currently working on this issue.
