### ISSUE TITLE
Read/show assignment deadline in user's time zone

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#3]
Right now it is displayed in the local time zone but one needs to input it in UTC (https://codecheck.io/newAssignment, https://codecheck.io/private/editAssignment/id/key)

```
new Date().getTimezoneOffset()
Intl.DateTimeFormat().resolvedOptions().timeZone
```
Show both local time and UTC?

**Comment by odiaz95012** [comment]
I would like to work on implementing this.

**Comment by cayhorstmann** [comment]
This is in JavaScript, hope that's ok. The code is in `public/editAssignment.js`.

**Comment by cayhorstmann** [comment]
It may be easier to compute
```
request.deadline =  new Date(deadlineDate + ' ' + deadlineTime + ':59').toIsoString()
```
