### ISSUE TITLE
Filter out "bad words" from CodeCheck IDs

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#4]
I am concerned about anal, babe, nude, sexy. Look at grep -E '^(([aeiouy][bcdfghjklmnpqrstvwxz]){2}|([bcdfghjklmnpqrstvwxz][aeiouy]){2})$' /usr/share/dict/words and find all objectionable words, then make sure they don't get generated.

**Comment by odiaz95012** [comment]
I am currently working on solving this issue.
