### ISSUE TITLE
Fix "Cannot edit problem with directories"

### ISSUE THREAD

**Issue by jmr-ua-pt** [cayhorstmann/codecheck2#40]
Currently, one can submit a ZIP file to https://codecheck.io/assets/uploadProblem.html, and that archive may contain files in subdirectories.  This works fine, as [this example](https://codecheck.io/files/2210160914k0sui6lkdooqm1guz1h65lzg) shows.

However, when one tries to [edit the problem](https://codecheck.io/private/problem/2210160914k0sui6lkdooqm1guz1h65lzg/4KRC3U65EVX1OQCRG1O2UD1P9), the message `Cannot edit problem with directories` is displayed.  This seems unwarranted and is very annoying, as fixing even a small typo will require creating a new problem altogether.  Why shouldn't I be able to send a new ZIP or edit files in subdirectories (with names such as `dir/file`)?

(As a workaround, when developing a new problem, I generally start by a submitting a simple file, then I follow the Edit URL and I upload the ZIP file and leave the browser open.  Then, if I spot a typo, I can press the browser button to get back to the Edit URL page and send an updated ZIP.)

**Comment by cayhorstmann** [comment]
This should now work (in staging, codecheck.me). Path separator is /

**Comment by jmr-ua-pt** [comment]
I just edited my [example problem](https://codecheck.me/private/problem/2210160914k0sui6lkdooqm1guz1h65lzg/4KRC3U65EVX1OQCRG1O2UD1P9) (on codecheck.me), and it worked fine.

Strangely, when I access the [public URL](https://codecheck.me/files/2210160914k0sui6lkdooqm1guz1h65lzg) and execute, I get this error:

```
System Error:

java.util.NoSuchElementException: solutionrun2/_run
	at com.horstmann.codecheck.Plan.outerr(Plan.java:115)
        ...
```

When I use the [codecheck.io public URL](https://codecheck.io/files/2210160914k0sui6lkdooqm1guz1h65lzg), though, the modifications are there and executing works.

**Comment by cayhorstmann** [comment]
Thanks for your patience with this. I fixed that problem, and now the public URL works on codecheck.me.

**Comment by jmr-ua-pt** [comment]
Great. It seems to be working fine now.
Thanks a lot.
