### ISSUE TITLE
Allow copying read-only code

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#67]
Why is copying of readonly code disabled? Perhaps because one cannot copy the entire file but only each editable or readonly area? Consider enabling copying, even if it must be done one area at a time.

**Comment by sgilbert-student** [comment]
Hi Cay. Actually, copying the read-only code is not disabled. It copies just fine. What is disabled is the feedback in the editor. You can click in a disabled area, drag the mouse to the end and then press Control-C. Even though there is no feedback, the data is actually copied. I've had to walk through this several times in class for my students.

**Comment by cayhorstmann** [comment]
Thanks Steve. There is something in the code that actively turned off the cursor and highlighting in the non-editable areas with some Ace editor voodoo. I can't remember why, but there must have been a reason to go through all that trouble. If you had to instruct students to fight this, that reason may not have been very good. I just pushed a change where you do see the cursor and the highlighting. Can you let me know if this is better?

**Comment by stephendgilbert** [comment]
Yes, it seems to work now, so you can probably close the issue.
