### ISSUE TITLE
Instructor feedback

### ISSUE THREAD

**Issue by cayhorstmann** [cayhorstmann/codecheck2#8]
When viewing a student assignment, instructors would like to leave feedback. Provide an edit field per problem and display it in the student view.

**Comment by charlesnguyen8** [comment]
I would like to work on this problem next.

**Comment by cayhorstmann** [comment]
This is not an easy issue. Get started by understanding assignments (https://horstmann.com/codecheck/assignments.html). Then determine which UI elements need to be changed. Which JavaScript files produce them? Next, where do those comments get stored in the database? Familiarize yourself with these issues, and we'll discuss an implementation strategy.
